model_name_or_path: Qwen/Qwen2.5-Coder-3B-Instruct
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: starcoder_rust
template: qwen
cutoff_len: 2048
max_samples: 100000
preprocessing_num_workers: 16

output_dir: train_2024-12-03-16-45-31
logging_steps: 10
save_steps: 500
plot_loss: true

per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
max_grad_norm: 1.0
val_size: 0

bf16: true
quantization_bit: 4
quantization_method: bitsandbytes
